server.port=8084
spring.application.name=loanservice
spring.datasource.url=jdbc:h2:mem:loandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sundx
spring.datasource.password=Poker@930
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.com.bank.loanservice=INFO
